# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0010_auto_20170305_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='.static/media/images/'),
        ),
    ]
