# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0015_auto_20170325_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images'),
        ),
    ]
