# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zhihu', '0018_auto_20170330_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('headImg', models.FileField(upload_to=upload.models.upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihu.User')),
            ],
        ),
    ]
