# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zhihu', '0014_auto_20170318_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_text', models.CharField(max_length=1000)),
                ('ans_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_title', models.CharField(max_length=30)),
                ('ques_description', models.CharField(max_length=500)),
                ('ques_tags', models.ManyToManyField(blank=True, to='zhihu.Tag')),
                ('ques_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(blank=True, to='focuses.Answer')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='focuses.Question')),
            ],
        ),
    ]
